/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "MemoryMapping.h"
#include "Buzzer.h"
#include "Fuel.h"
#include "HeadAndParkingLights.h"
#include "Indicators.h"
#include "USART.h"
#include "LCD.h"

uint8_t count1, count2, count3;
uint32_t result;
uint32_t FUEL_LEVEL_INDICATOR, USART;
uint8_t duty=0;
int res;
char character = 'j';
char message;
char str[100];

void delay()
{
	for(uint32_t i = 0 ; i < 300000; i++);
}

int main()
{
	LcdInit();
	GPIOConfigurationSwitch();
	USARTInit();
	Fuel();

	uint32_t IGNITION_SWITCH, RIGHT_INDICATOR_SWITCH,LEFT_INDICATOR_SWITCH,HEAD_LIGHT_SWITCH;

	RCC->AHB1ENR |=  (7<<0);

	while(1)
	{
		TIM1->CCR2 =(uint32_t) TIM1->ARR * 0/100;
		TIM1->CCR3 =(uint32_t) TIM1->ARR * 0/100;
		TIM1->CCR3 =(uint32_t) TIM1->ARR * 0/100;

		RIGHT_INDICATOR_SWITCH = (uint8_t)(GPIOB->IDR & (1<<7)); // sw1
		IGNITION_SWITCH        = (uint8_t)(GPIOB->IDR & (1<<3)); //sw2
		LEFT_INDICATOR_SWITCH  = (uint8_t)(GPIOB->IDR  & (1<<4)); //sw3
		HEAD_LIGHT_SWITCH      = (uint16_t)(GPIOA->IDR  & (1<<15)); //sw4

		LcdFxn(0,0x01);
		lprint(0xC0,"CAROFF");
		delay();

		//to turn  on the PB 13 LED
		//TID30
		if(IGNITION_SWITCH == 0)
		{
			LcdFxn(0,0x01);
			lprint(0x80,"CARON");
			delay();

			//GPIOB->ODR &=~( 1 << 13);

			while(1)
			{
				ADC1->CR2 |=(1<<30);// Start conversion of regular channels
				while(!(ADC1->SR & 2));

				result = (uint32_t)(ADC1->DR);

				FUEL_LEVEL_INDICATOR=(result*100)/4095;
				sprintf(str,"FUEL:");
				lprint(0xC0, str);
				itoa(FUEL_LEVEL_INDICATOR, str, 10);
				lprint(0xC6,str);

				USART = (USART3->SR & (1<<5));

				if(USART==32)
					lprint(0x86,"U:OK");//SRS160---TID160
				else
					lprint(0x86,"U:NO");////SRS170---TID170

				USARTWrite(character);
				message = USARTRead();


				RIGHT_INDICATOR_SWITCH = (uint8_t)(GPIOB->IDR & (1<<7)); // sw1
				IGNITION_SWITCH = (uint8_t)(GPIOB->IDR & (1<<3)); //sw2
				LEFT_INDICATOR_SWITCH = (uint8_t)(GPIOB->IDR  & (1<<4)); //sw3
				HEAD_LIGHT_SWITCH = (uint16_t)(GPIOA->IDR  & (1<<15)); //sw4

				TIM3->CCR1 =(uint32_t) TIM3->ARR * duty/100;

				//to turn OFF the LED
				//TID40
				if( IGNITION_SWITCH == 0)
				{
					LcdFxn(0,0x01);
					GPIOB->ODR |=( 1 << 13);
					delay();

					TIM1->CCR2 =(uint32_t) TIM1->ARR * 0/100;
					delay();

					TIM1->CCR3 =(uint32_t) TIM1->ARR * 0/100;
					delay();

					BuzzerOFF();
					delay();

					break;
				}


				//SWITCH 1------> presss------>RIGHT indicator--->with 0.5 duty cycle
				//and BUZZER with 50 % duty cycle
				//TID80
				if(RIGHT_INDICATOR_SWITCH == 0 )
				{
					BuzzerOFF();
					LcdFxn(0,0x01);
					lprint(0x80,"RIGHT");
					delay();
					//LcdFxn(0,0x01);
					count1++;
					//RIGHT_INDICATOR();
					//TIM1->CCR2 =(uint32_t) TIM1->ARR * 50/100; // load duty cycle for PWM
					BuzzerON();

					//TID90
					if(count1 == 2)
					{
						//TIM1->CCR2 =(uint32_t) TIM1->ARR * 0/100;
						BuzzerOFF();
						LcdFxn(0,0x01);
						lprint(0x80,"CARON");
						delay();

						count1=0;
					}
				}
				//SWITCH 3------> presss------>LEFT indicator--->with 0.5 duty cycle
				//and BUZZER with 50 % duty cycle
				//TID100
				if(LEFT_INDICATOR_SWITCH == 0 )
				{
					BuzzerOFF();
					LcdFxn(0,0x01);
					lprint(0x80,"LEFT");
					delay();
					//LcdFxn(0,0x01);
					count2++;
				   // LEFT_INDICATOR();
				   // TIM1->CCR3 =(uint32_t) TIM1->ARR * 50/100; // load duty cycle for PWM
					BuzzerON();
				   // TIM3->CCR4 =(uint32_t) TIM3->ARR * 50/100;
					//TID110
					if(count2==2)
					{
				   // TIM1->CCR3 =(uint32_t) TIM1->ARR * 0/100;
						BuzzerOFF();
						LcdFxn(0,0x01);
						lprint(0x80,"CARON");
						delay();

						count2=0;
					}
				}
				//SWITCH 4----.press
				//i- LED with 10 % intenstity
				//ii- again press--. LED with 90% intensity
				//iii-Again press-->Both the indicatore on simultaneously
				if(HEAD_LIGHT_SWITCH == 0 )
				{
					BuzzerOFF();
					//LcdFxn(0,0x01);
					count3++;

					//TID120
					if(count3 ==1)
					{
						//duty=90;
						LcdFxn(0,0x01);
						lprint(0x80,"LOBEAM");
						delay();
					}

					//TID130
					if(count3==2)
					{
					    // duty=10;
						LcdFxn(0,0x01);
						lprint(0x80,"HIBEAM");
						delay();
					}

					//TID140
					if(count3 ==3)
					{
						//TIM1->CR1 |=(1<<0);
						LcdFxn(0,0x01);
						lprint(0x80,"PARK");
						delay();
						//LEFT_INDICATOR();
						//TIM1->CCR2 =(uint32_t) TIM1->ARR * 50/100;
						BuzzerON();
					   // TIM3->CCR4 =(uint32_t) TIM3->ARR * 50/100;
						//RIGHT_INDICATOR();
						//TIM1->CCR3 =(uint32_t) TIM1->ARR * 50/100;
					}

					//TID150
					if(count3 == 4)
					{
						BuzzerOFF();
						LcdFxn(0,0x01);
						lprint(0x80,"CARON");
						delay();
						//duty=100;
						//delay();
						//TIM1->CCR2 =(uint32_t) TIM1->ARR * 0/100;
						//TIM1->CCR3 =(uint32_t) TIM1->ARR * 0/100;

						count3 = 0;
					}

					HeadAndParkingLights();
					delay();
				}
			}
		}
	}
}
